MVCMusicStore/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCMusicStore.Models
{
    public class Genre : EntityBase
    {
         [Required(ErrorMessage = "Genre name cannot be empty"), StringLength(50, ErrorMessage = "Allowed character count is 50 for Genre Name")]
        public string Name { get; set; }
        public string Description { get; set; }

        //Mapping
        public virtual List<Album> Albums { get; set; }
    }
}

MVCMusicStore/Controllers/GenreManagerController.cs
using MVCMusicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MVCMusicStore.Controllers
{
    public class GenreManagerController : Controller
    {
        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _GenreList(int? page)
        {
            var genres = db.Genres.ToList();
            if (genres.Count <= 0)
            {
                ViewBag.State = "empty";
                return PartialView();
            }
            return PartialView(genres.ToPagedList(page ?? 1, 3));
        }

        public ActionResult AddGenre()
        {
            ViewBag.Process = "AddGenre";
            return PartialView("_GenreForm");
        }

        [HttpPost]
        public ActionResult AddGenre(Genre genre, int? page)
        {
            db.Genres.Add(genre);
            db.SaveChanges();
            return PartialView("_GenreList", db.Genres.ToList().ToPagedList(page ?? 1, 3));
        }

        public ActionResult UpdateGenre(int genreId)
        {
            ViewBag.Process = "UpdateGenre";
            return PartialView("_GenreForm", db.Genres.Find(genreId));
        }

        [HttpPost]
        public ActionResult UpdateGenre(Genre genre, int? page)
        {
            Genre updated = db.Genres.Find(genre.Id);
            db.Entry(updated).CurrentValues.SetValues(genre);
            db.SaveChanges();
            return PartialView("_GenreList", db.Genres.ToList().ToPagedList(page ?? 1, 3));
        }

        public ActionResult DeleteGenre(int genreId, int? page)
        {
            db.Genres.Remove(db.Genres.Find(genreId));
            db.SaveChanges();
            var genres = db.Genres.ToList().ToPagedList(page ?? 1, 3);
            if (genres.Count <= 0)
            {
                return PartialView("_GenreList", db.Genres.ToList().ToPagedList(page - 1 ?? 1, 3));
            }
            return PartialView("_GenreList", genres);
        }

    }
}

MVCMusicStore/Views/GenreManager/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-box-header">
    <h3>Manage Genres</h3>
    <ul class="content-box-tabs">
        <li><a href="#tab1" id="firstTab" class="default-tab">List</a></li>
        <li><a href="#tab2" id="secondTab">Form</a></li>
    </ul>
    <div class="clear">
    </div>
</div>
<div class="content-box-content">
    <div class="tab-content default-tab" id="tab1">
        @Html.Action("_GenreList", "GenreManager")
    </div>
    <div class="tab-content" id="tab2">
        @Html.Action("AddGenre", "GenreManager")
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#main-nav a").removeClass("current");
        $("#genre").addClass("current");
    });
    function GetForm() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("AddGenre", "GenreManager")',
            data: {},
            success: function (data) {
                $("#tab2").html(data);
                $("#firstTab").removeClass('current');
                $("#secondTab").addClass('current');
                $("#tab2").show();
                $("#tab1").hide();
            }
        });
    }
    function GetPage(page) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("_GenreList", "GenreManager")',
            data: { page: page },
            success: function (data) {
                $("#tab1").html(data);
                $("#tab1 table tbody tr").removeClass("alt-row");
                $("#tab1 table tbody tr:even").addClass("alt-row");
                $(".pagination a.number").removeClass("current");
                $(".pagination a[title='" + page + "']").addClass("current");
            }
        });
    }

    function DefaultView() {
        $("#Name").val('');
        $("#Description").val('');
        BackToList();
        $("#tab1 table tbody tr").removeClass("alt-row");
        $("#tab1 table tbody tr:even").addClass("alt-row");
    }

    function BackToList() {
        $("#secondTab").removeClass('current');
        $("#firstTab").addClass('current');
        $("#tab1").show();
        $("#tab2").hide();
    }

    function SendGenre(id) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("UpdateGenre", "GenreManager")',
            data: { genreId: id },
            success: function (data) {
                $("#tab2").html(data);
                $("#firstTab").removeClass('current');
                $("#secondTab").addClass('current');
                $("#tab2").show();
                $("#tab1").hide();
            }
        });
    }

    function DeleteGenre(id) {
        //var tempScrollTop = $(window).scrollTop();
        var result = confirm("Do you want to delete this genre?");
        var pageNumber = $(".pagination a.current").attr("title");
        if (result) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("DeleteGenre", "GenreManager")',
                    data: { genreId: id, page: pageNumber },
                    success: function (data) {
                        $("#tab1").html(data);
                        $("#tab1 table tbody tr").removeClass("alt-row");
                        $("#tab1 table tbody tr:even").addClass("alt-row");
                        // $(window).scrollTop(tempScrollTop);
                        //$("body").animate({ scrollTop: tempScrollTop }, 500);
                    }
                });
            }
        }
</script>

MVCMusicStore/Views/GenreManager/_GenreForm.cshtml
@model MVCMusicStore.Models.Genre
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        var actionName = $("#formum").attr('action');
        var pagenumber = $(".pagination a.current").attr("title");
        $("#formum").attr("action", actionName + "&page=" + pagenumber);
    });
</script>
@using (Ajax.BeginForm((string)ViewBag.Process, "GenreManager", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "tab1",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "DefaultView"
}, new { id="formum"}))
{
    <fieldset>
        @if (Model != null)
        {
            @Html.HiddenFor(model => model.Id)
        }
        <p>
            <label>Genre Name</label>
            @Html.TextBoxFor(model => model.Name, new { @class = "text-input small-input" })
            @Html.ValidationMessageFor(model => model.Name)
        </p>
        <p>
            <label>Description</label>
            @Html.TextAreaFor(model => model.Description, new { @class = "text-input textarea", cols = "79", rows = "5" })
            @Html.ValidationMessageFor(model => model.Description)
        </p>

        <p>
            <input class="button" type="button" value="Back To List" id="btnBackToList" onclick="BackToList()" />
            <input class="button" type="submit" value="Save" id="btnSave" />
        </p>
    </fieldset>
    <div class="clear">
    </div>
}

MVCMusicStore/Views/GenreManager/_GenreList.cshtml
@model IPagedList<Genre>
<p>
    <input type="button" class="button" value="Create New genre" id="btnNew" onclick="GetForm()" />
</p>
@if (ViewBag.State == "empty")
{
    <table>
        <thead>
            <tr>
                <th>There is no genre in database.If you want to add new genre use Create New Genre button.
                </th>
            </tr>
        </thead>
    </table>
}
else
{ 
    <table>
        <thead>
            <tr>
                <th>Genre Name
                </th>
                <th>Description
                </th>
                <th>Created Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="4">
                    <div class="pagination">

                        @if (Model.HasPreviousPage)
                        {
                            <a href="javascript:void(0);" title="First Page" onclick="GetPage(1)">&laquo; First</a>
                            <a href="javascript:void(0);" title="Previous Page" onclick="GetPage(@(Model.PageNumber - 1))">&laquo;Previous</a>
                        }
                        else
                        {
                            <a href="javascript:void(0);" title="First Page">&laquo; First</a>
                            <a href="javascript:void(0);" title="Previous Page">&laquo;Previous</a>
                        }

                        @for (int i = 1; i < Model.PageCount+1; i++)
                        {
                            if (i == Model.PageNumber)
                            {
                            <a href="javascript:void(0);" class="number current" title="@i" onclick="GetPage(@i)">@i</a>
                                continue;
                            }
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@i)" title="@i">@i</a>
                        }

                        @if (Model.HasNextPage)
                        {
                            <a href="javascript:void(0);" title="Next Page" onclick="GetPage(@(Model.PageNumber + 1))">Next &raquo;</a>
                            <a href="javascript:void(0);" title="Last Page" onclick="GetPage(@(Model.PageCount))">Last &raquo;</a>
                        }
                        else
                        {
                            <a href="javascript:void(0);" title="Next Page">Next &raquo;</a>
                            <a href="javascript:void(0);" title="Last Page">Last &raquo;</a>
                        }
                    </div>
                    <!-- End .pagination -->
                    <div class="clear">
                    </div>
                </td>
            </tr>
        </tfoot>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>@item.CreatedDate.ToShortDateString()
                    </td>
                    <td>
                        <a href="javascript:void(0);" title="Edit" onclick="SendGenre(@item.Id)">
                            <img src='@Url.Content("~/Content/resources/images/icons/pencil.png")' alt="Edit" /></a> <a href="javascript:void(0);" title="Delete" onclick="DeleteGenre(@item.Id)">
                                <img src='@Url.Content("~/Content/resources/images/icons/cross.png")' alt="Delete" /></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}