MVCMusicStore/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCMusicStore.Models
{
    public class Artist : EntityBase
    {
        [Required(ErrorMessage = "Artist name cannot be empty"), StringLength(150, ErrorMessage = "Allowed character count is 150 for Artist Name")]
        public string Name { get; set; }
        public int? Rating { get; set; }

        //Mapping
        public virtual List<Album> Albums { get; set; }
    }
}

MVCMusicStore/Controllers/ArtistManagerController.cs
using MVCMusicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MVCMusicStore.Controllers
{
    public class ArtistManagerController : Controller
    {
        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _ArtistList(int? page)
        {
            var artists = db.Artists.ToList();
            if (artists.Count <= 0)
            {
                ViewBag.State = "empty";
                return PartialView();
            }
            return PartialView(artists.ToPagedList(page ?? 1, 5));
        }

        public ActionResult AddArtist()
        {
            ViewBag.Process = "AddArtist";
            return PartialView("_ArtistForm");
        }

        [HttpPost]
        public ActionResult AddArtist(Artist artist, int? page)
        {
            db.Artists.Add(artist);
            db.SaveChanges();
            return PartialView("_ArtistList", db.Artists.ToList().ToPagedList(page ?? 1, 5));
        }

        public ActionResult UpdateArtist(int artistId)
        {
            ViewBag.Process = "UpdateArtist";
            return PartialView("_ArtistForm", db.Artists.Find(artistId));
        }

        [HttpPost]
        public ActionResult UpdateArtist(Artist artist, int? page)
        {
            Artist updated = db.Artists.Find(artist.Id);
            db.Entry(updated).CurrentValues.SetValues(artist);
            db.SaveChanges();
            return PartialView("_ArtistList", db.Artists.ToList().ToPagedList(page ?? 1, 5));
        }

        public ActionResult DeleteArtist(int artistId, int? page)
        {
            db.Artists.Remove(db.Artists.Find(artistId));
            db.SaveChanges();
            var artists = db.Artists.ToList().ToPagedList(page ?? 1, 5);
            if (artists.Count <= 0)
            {
                return PartialView("_ArtistList", db.Artists.ToList().ToPagedList(page - 1 ?? 1, 5));
            }
            return PartialView("_ArtistList", artists);
        }

    }
}

MVCMusicStore/Views/ArtistManager/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-box-header">
    <h3>Manage Artists</h3>
    <ul class="content-box-tabs">
        <li><a href="#tab1" id="firstTab" class="default-tab">List</a></li>
        <li><a href="#tab2" id="secondTab">Form</a></li>
    </ul>
    <div class="clear">
    </div>
</div>
<div class="content-box-content">
    <div class="tab-content default-tab" id="tab1">
        @Html.Action("_ArtistList", "ArtistManager")
    </div>
    <div class="tab-content" id="tab2">
        @Html.Action("AddArtist", "ArtistManager")
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#main-nav a").removeClass("current");
        $("#artist").addClass("current");
    });
    function GetForm() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("AddArtist", "ArtistManager")',
            data: {},
            success: function (data) {
                $("#tab2").html(data);
                $("#firstTab").removeClass('current');
                $("#secondTab").addClass('current');
                $("#tab2").show();
                $("#tab1").hide();
            }
        });
    }
    function GetPage(page) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("_ArtistList", "ArtistManager")',
            data: { page: page },
            success: function (data) {
                $("#tab1").html(data);
                $("#tab1 table tbody tr").removeClass("alt-row");
                $("#tab1 table tbody tr:even").addClass("alt-row");
                $(".pagination a.number").removeClass("current");
                $(".pagination a[title='" + page + "']").addClass("current");
            }
        });
    }

    function DefaultView() {
        $("#Name").val('');
        BackToList();
        $("#tab1 table tbody tr").removeClass("alt-row");
        $("#tab1 table tbody tr:even").addClass("alt-row");
    }

    function BackToList() {
        $("#secondTab").removeClass('current');
        $("#firstTab").addClass('current');
        $("#tab1").show();
        $("#tab2").hide();
    }

    function SendArtist(id) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("UpdateArtist", "ArtistManager")',
                data: { artistId: id },
                success: function (data) {
                    $("#tab2").html(data);
                    $("#firstTab").removeClass('current');
                    $("#secondTab").addClass('current');
                    $("#tab2").show();
                    $("#tab1").hide();
                }
            });
        }

        function DeleteArtist(id) {
            //var tempScrollTop = $(window).scrollTop();
            var result = confirm("Do you want to delete this Artist?");
            var pageNumber = $(".pagination a.current").attr("title");
            if (result) {
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("DeleteArtist", "ArtistManager")',
                    data: { artistId: id, page: pageNumber },
                    success: function (data) {
                        $("#tab1").html(data);
                        $("#tab1 table tbody tr").removeClass("alt-row");
                        $("#tab1 table tbody tr:even").addClass("alt-row");
                        // $(window).scrollTop(tempScrollTop);
                        //$("body").animate({ scrollTop: tempScrollTop }, 500);
                    }
                });
            }
        }
</script>

MVCMusicStore/Views/ArtistManager/_ArtistForm.cshtml
@model MVCMusicStore.Models.Artist
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        var actionName = $("#formum").attr('action');
        var pagenumber = $(".pagination a.current").attr("title");
        $("#formum").attr("action", actionName + "&page=" + pagenumber);
    });
</script>
@using (Ajax.BeginForm((string)ViewBag.Process, "ArtistManager", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "tab1",
    InsertionMode = InsertionMode.Replace,
    OnSuccess = "DefaultView"
}, new { id="formum"}))
{
    <fieldset>
        @if (Model != null)
        {
            @Html.HiddenFor(model => model.Id)
        }
        <p>
            <label>Artist Name</label>
            @Html.TextBoxFor(model => model.Name, new { @class = "text-input small-input" })
            @Html.ValidationMessageFor(model => model.Name)
        </p>

        <p>
            <input class="button" type="button" value="Back To List" id="btnBackToList" onclick="BackToList()" />
            <input class="button" type="submit" value="Save" id="btnSave" />
        </p>
    </fieldset>
    <div class="clear">
    </div>
}

MVCMusicStore/Views/ArtistManager/_ArtistList.cshtml
@model IPagedList<Artist>
<p>
    <input type="button" class="button" value="Create New Artist" id="btnNew" onclick="GetForm()" />
</p>
@if (ViewBag.State == "empty")
{
    <table>
        <thead>
            <tr>
                <th>There is no artist in database.If you want to add new artist use Create New Artist button.
                </th>
            </tr>
        </thead>
    </table>
}
else
{ 
    <table>
        <thead>
            <tr>
                <th>Artist Name
                </th>
                <th>Created Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">
                    <div class="pagination">

                        @if (Model.HasPreviousPage)
                        {
                            <a href="javascript:void(0);" title="First Page" onclick="GetPage(1)">&laquo; First</a>
                            <a href="javascript:void(0);" title="Previous Page" onclick="GetPage(@(Model.PageNumber - 1))">&laquo;Previous</a>
                        }
                        else
                        {
                            <a href="javascript:void(0);" title="First Page">&laquo; First</a>
                            <a href="javascript:void(0);" title="Previous Page">&laquo;Previous</a>
                        }
                        @if (Model.PageCount <= 13)
                        {
                            for (int i = 1; i < Model.PageCount + 1; i++)
                            {
                                if (i == Model.PageNumber)
                                {
                            <a href="javascript:void(0);" class="number current" title="@i" onclick="GetPage(@i)">@i</a>
                                    continue;
                                }
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@i)" title="@i">@i</a>
                            }
                        }
                        else
                        {
                            if (Model.PageNumber <= 6)
                            {
                                for (int i = 1; i <= 9; i++)
                                {
                                    if (i == Model.PageNumber)
                                    {
                            <a href="javascript:void(0);" class="number current" title="@i" onclick="GetPage(@i)">@i</a>
                                        continue;
                                    }
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@i)" title="@i">@i</a>
                                }
                            <a>...</a>
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@(Model.PageCount - 1))" title="@(Model.PageCount - 1)">@(Model.PageCount - 1)</a>
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@Model.PageCount)" title="@Model.PageCount">@Model.PageCount</a>
                            
                            }
                            else if (Model.PageNumber >= Model.PageCount - 5)
                            {
                            <a href="javascript:void(0);" class="number" onclick="GetPage(1)" title="1">1</a>
                            <a href="javascript:void(0);" class="number" onclick="GetPage(2)" title="2">2</a>
                            <a>...</a>
                                for (int i = Model.PageCount - 10; i <= Model.PageCount; i++)
                                {
                                    if (i == Model.PageNumber)
                                    {
                            <a href="javascript:void(0);" class="number current" title="@i" onclick="GetPage(@i)">@i</a>
                                        continue;
                                    }
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@i)" title="@i">@i</a>
                                }
                            }
                            else
                            {
                            <a href="javascript:void(0);" class="number" onclick="GetPage(1)" title="1">1</a>
                            <a href="javascript:void(0);" class="number" onclick="GetPage(2)" title="2">2</a>
                            <a>...</a>
                                for (int i = Model.PageNumber - 2; i <= Model.PageNumber + 2; i++)
                                {
                                    if (i == Model.PageNumber)
                                    {
                            <a href="javascript:void(0);" class="number current" title="@i" onclick="GetPage(@i)">@i</a>
                                        continue;
                                    }
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@i)" title="@i">@i</a>
                                }
                            <a>...</a>
                           <a href="javascript:void(0);" class="number" onclick="GetPage(@(Model.PageCount - 1))" title="@(Model.PageCount - 1)">@(Model.PageCount - 1)</a>
                            <a href="javascript:void(0);" class="number" onclick="GetPage(@Model.PageCount)" title="@Model.PageCount">@Model.PageCount</a>
                            }
                        }
                        @if (Model.HasNextPage)
                        {
                            <a href="javascript:void(0);" title="Next Page" onclick="GetPage(@(Model.PageNumber + 1))">Next &raquo;</a>
                            <a href="javascript:void(0);" title="Last Page" onclick="GetPage(@(Model.PageCount))">Last &raquo;</a>
                        }
                        else
                        {
                            <a href="javascript:void(0);" title="Next Page">Next &raquo;</a>
                            <a href="javascript:void(0);" title="Last Page">Last &raquo;</a>
                        }
                    </div>
                    <!-- End .pagination -->
                    <div class="clear">
                    </div>
                </td>
            </tr>
        </tfoot>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name
                    </td>
                    <td>@item.CreatedDate.ToShortDateString()
                    </td>
                    <td>
                        <a href="javascript:void(0);" title="Edit" onclick="SendArtist(@item.Id)">
                            <img src='@Url.Content("~/Content/resources/images/icons/pencil.png")' alt="Edit" /></a> <a href="javascript:void(0);" title="Delete" onclick="DeleteArtist(@item.Id)">
                                <img src='@Url.Content("~/Content/resources/images/icons/cross.png")' alt="Delete" /></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}