MVCMusicStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStore.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCMusicStore/Controllers/AlbumManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MVCMusicStore.Models;
using MVCMusicStore.Tools;
using System.Web.Script.Serialization;

namespace MVCMusicStore.Controllers
{
    [Authorize (Roles ="Admin")]
    public class AlbumManagerController : Controller
    {
        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _AlbumList(int? page)
        {
            var albums = db.Albums.ToList();
            if (albums.Count <= 0)
            {
                ViewBag.State = "empty";
                return PartialView();
            }
            return PartialView(albums.ToPagedList(page ?? 1, 10));
        }

        public ActionResult AddAlbum()
        {
            ViewBag.Artists = db.Artists.ToList();
            ViewBag.Genres = db.Genres.ToList();
            ViewBag.Process = "AddAlbum";
            return PartialView("_AlbumForm");
        }

        [HttpPost]
        public ActionResult AddAlbum(Album album, int? page)
        {
            ViewBag.Artists = db.Artists.ToList();
            ViewBag.Genres = db.Genres.ToList();
            db.Albums.Add(album);
            db.SaveChanges();
            return PartialView("_AlbumList", db.Albums.ToList().ToPagedList(page ?? 1, 10));
        }

        public ActionResult UpdateAlbum(int albumId)
        {
            ViewBag.Artists = db.Artists.ToList();
            ViewBag.Genres = db.Genres.ToList();
            ViewBag.Process = "UpdateAlbum";
            return PartialView("_AlbumForm", db.Albums.Find(albumId));
        }

        [HttpPost]
        public ActionResult UpdateAlbum(Album album, int? page)
        {
            ViewBag.Artists = db.Artists.ToList();
            ViewBag.Genres = db.Genres.ToList();
            if (!ModelState.IsValid)
                return PartialView("_AlbumForm", album);
            Album updated = db.Albums.Find(album.Id);
            db.Entry(updated).CurrentValues.SetValues(album);
            db.SaveChanges();
            return PartialView("_AlbumList", db.Albums.ToList().ToPagedList(page ?? 1, 10));
        }

        public ActionResult DeleteAlbum(int albumId, int? page)
        {
            Album album = db.Albums.Find(albumId);
            if (album.AlbumArtUrl != "/Content/Images/placeholder.gif")
                System.IO.File.Delete(Server.MapPath(album.AlbumArtUrl));
            db.Albums.Remove(album);
            db.SaveChanges();
            var albums = db.Albums.ToList().ToPagedList(page ?? 1, 10);
            if (albums.Count <= 0)
            {
                return PartialView("_AlbumList", db.Albums.ToList().ToPagedList(page - 1 ?? 1, 10));
            }
            return PartialView("_AlbumList", albums);
        }

        public string AddPicture(int id, string data)
        {
            PictureToSave pictureToSave = new JavaScriptSerializer().Deserialize(data, typeof(PictureToSave)) as PictureToSave;
            string imagePath = "/Content/AlbumImages/" + Guid.NewGuid().ToString().Replace("-", "").Substring(0, 5) + ".jpg";
            pictureToSave.SmallPicture.Save(Server.MapPath(imagePath));
            if (id > 0)
            {
                Album album = db.Albums.Find(id);
                if (album.AlbumArtUrl != "/Content/Images/placeholder.gif")
                    System.IO.File.Delete(Server.MapPath(album.AlbumArtUrl));
            }
            return imagePath;
        }
    }
}

MVCMusicStore/Controllers/CartController.cs
using MVCMusicStore.Models;
using MVCMusicStore.Tools;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MVCMusicStore.Controllers
{
    public class CartController : Controller
    {

        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _CartButton()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AddToCart(int albumId)
        {
            MyCart myCart = Session["cart"] as MyCart;
            Album added = db.Albums.Find(albumId);
            myCart.AddToCart(new CartItem
            {
                Count = 1,
                Id = albumId,
                Name = added.Title,
                Price = added.Price
            });
            return PartialView("_CartButton");
        }

        public ActionResult _CartItems()
        {
            MyCart myCart = Session["cart"] as MyCart;
            return PartialView(myCart.CartItems);
        }

        public ActionResult RemoveFromCart(int albumId)
        {
            MyCart myCart = Session["cart"] as MyCart;
            myCart.RemoveFromcart(albumId);
            Session["cart"] = myCart;
            return Json(new
            {
                CartButton = RenderRazorViewToString("_CartButton", null),
                CartTable = RenderRazorViewToString("_CartItems", myCart.CartItems).ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Checkout()
        {
            MyCart myCart = Session["cart"] as MyCart;
            UserDetail currentUser = db.UserDetails.Find(WebSecurity.CurrentUserId);
            Tuple<MyCart, UserDetail> t = new Tuple<MyCart, UserDetail>(myCart, currentUser);
            return View(t);
        }

        [HttpPost, ActionName("Checkout")]
        public ActionResult ConfirmCheckout()
        {
            MyCart myCart = Session["cart"] as MyCart;
            UserDetail currentUser = db.UserDetails.Find(WebSecurity.CurrentUserId);
            Order newOrder = new Order()
            {
                Email = currentUser.Email,
                Phone = currentUser.Phone,
                ShipAddress = currentUser.Address,
                UserDetailId = currentUser.Id
            };
            db.Orders.Add(newOrder);
            foreach (var item in myCart.CartItems)
            {
                OrderDetail od = new OrderDetail()
                {
                    Count = item.Count,
                    AlbumId = item.Id,
                    Discount = 0,
                    Order = newOrder,
                    Price = item.Price
                };
                db.OrderDetails.Add(od);
            }
            db.SaveChanges();
            myCart.ClearCart();
            return RedirectToAction("Index", "Home");
        }

        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

MVCMusicStore/Controllers/UserManagerController.cs
using MVCMusicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Data.Entity.Validation;

namespace MVCMusicStore.Controllers
{
    public class UserManagerController : Controller
    {
        MusicStoreEntities db = new MusicStoreEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _UserList(int? page)
        {
            var users = db.UserDetails.Where(ud => ud.IsDeleted == false).ToList();
            if (users.Count <= 0)
            {
                ViewBag.State = "empty";
                return PartialView();
            }
            return PartialView(users.ToPagedList(page ?? 1, 10));
        }

        [HttpPost]
        public ActionResult DeleteUser(int userId, int? page)
        {
            UserDetail user = db.UserDetails.Find(userId);
            user.IsDeleted = true;
            user.Password = user.ConfirmPassword = "asdf";
            db.SaveChanges();


            var users = db.UserDetails.Where(ud => ud.IsDeleted == false).ToList().ToPagedList(page ?? 1, 10);
            if (users.Count <= 0)
            {
                return PartialView("_UserList", db.UserDetails.ToList().Where(ud => ud.IsDeleted == false).ToPagedList(page - 1 ?? 1, 10));
            }
            return PartialView("_UserList", users);
        }

        [HttpPost]
        public ActionResult BanUser(int userId, int? page)
        {
            UserDetail user = db.UserDetails.Find(userId);
            user.IsLocked = true;
            user.Password = user.ConfirmPassword = "asdf";
            db.SaveChanges();
            return PartialView("_UserList", db.UserDetails.Where(ud=>ud.IsDeleted==false).ToList().ToPagedList(page ?? 1, 10));
        }

        [HttpPost]
        public ActionResult ActivateUser(int userId, int? page)
        {
            UserDetail user = db.UserDetails.Find(userId);
            user.IsLocked = false;
            user.Password = user.ConfirmPassword = "asdf";
            db.SaveChanges();
            return PartialView("_UserList", db.UserDetails.Where(ud => ud.IsDeleted == false).ToList().ToPagedList(page ?? 1, 10));
        }
    }
}

MVCMusicStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/AdminCss")
    @RenderSection("styles", required: false)
    <!--[if lte IE 7]>
            <link rel="stylesheet" href="resources/css/ie.css" type="text/css" media="screen" />
        <![endif]-->
</head>
<body>
    <div id="body-wrapper">
        <!-- Wrapper for the radial gradient background -->
        <div id="sidebar">
            <div id="sidebar-wrapper">
                <!-- Sidebar with logo and menu -->
                <h1 id="sidebar-title">
                    <a href="#">Simpla Admin</a></h1>
                <!-- Logo (221px wide) -->
                <a href="#">
                    <img id="logo" src='@Url.Content("~/Content/resources/images/logo.png")' alt="Simpla Admin logo" /></a>
                <!-- Sidebar Profile links -->
                <div id="profile-links">
                    Hello, <a href="#" title="Edit your profile">John Doe</a><br />
                    <br />
                    <a href='@Url.Action("Index", "Home")' title="View the Site">Back to Site</a> | <a href='@Url.Action("Logout", "Account")' title="Sign Out">Sign
                        Out</a>
                </div>
                <ul id="main-nav">
                    <li><a id="admin" href='@Url.Action("Index", "Admin")' class="nav-top-item no-submenu">Dashboard</a></li>
                    <li><a id="genre" href='@Url.Action("Index", "GenreManager")' class="nav-top-item no-submenu">Manage Genres</a></li>
                    <li><a id="artist" href='@Url.Action("Index", "ArtistManager")' class="nav-top-item no-submenu">Manage Artists</a></li>
                    <li><a id="album" href='@Url.Action("Index", "AlbumManager")' class="nav-top-item no-submenu">Manage Albums</a></li>
                    <li><a id="order" href='@Url.Action("Index", "OrderManager")' class="nav-top-item no-submenu">Manage Orders</a></li>
                    <li><a id="user" href='@Url.Action("Index", "UserManager")' class="nav-top-item no-submenu">Manage Users</a></li>
                </ul>
                <div id="messages" style="display: none">
                    <h3>3 Messages</h3>
                    <p>
                        <strong>17th May 2009</strong> by Admin<br />
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in
                        mi at felis aliquet congue. <small><a href="#" class="remove-link" title="Remove message">Remove</a></small>
                    </p>
                    <p>
                        <strong>2nd May 2009</strong> by Jane Doe<br />
                        Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at
                        sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam.
                        Vivamus pretium ornare est. <small><a href="#" class="remove-link" title="Remove message">Remove</a></small>
                    </p>
                    <p>
                        <strong>25th April 2009</strong> by Admin<br />
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in
                        mi at felis aliquet congue. <small><a href="#" class="remove-link" title="Remove message">Remove</a></small>
                    </p>
                    <form action="" method="post">
                        <h4>New Message</h4>
                        <fieldset>
                            <textarea class="textarea" name="textfield" cols="79" rows="5"></textarea>
                        </fieldset>
                        <fieldset>
                            <select name="dropdown" class="small-input">
                                <option value="option1">Send to...</option>
                                <option value="option2">Everyone</option>
                                <option value="option3">Admin</option>
                                <option value="option4">Jane Doe</option>
                            </select>
                            <input class="button" type="submit" value="Send" />
                        </fieldset>
                    </form>
                </div>
                <!-- End #messages -->
            </div>
        </div>
        <!-- End #sidebar -->
        <div id="main-content">
            <!-- Main Content Section with everything -->
            <noscript>
                <!-- Show a notification if the user has disabled javascript -->
                <div class="notification error png_bg">
                    <div>
                        Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/"
                            title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852"
                                title="Enable Javascript in your browser">enable</a> Javascript to navigate
                        the interface properly.
                    </div>
                </div>
            </noscript>
            <!-- Page Head -->
            <h2>Welcome John</h2>
            <p id="page-intro">
                What would you like to do?
            </p>
            <ul class="shortcut-buttons-set">
                <li><a class="shortcut-button" href='@Url.Action("Index", "GenreManager")'><span>
                    <img src='@Url.Content("~/Content/resources/images/icons/genres.png")' alt="icon" /><br />
                    Genres</span></a></li>
                <li><a class="shortcut-button" href='@Url.Action("Index", "ArtistManager")'><span>
                    <img src='@Url.Content("~/Content/resources/images/icons/artists.png")' alt="icon" /><br />
                    Artists</span></a></li>
                <li><a class="shortcut-button" href='@Url.Action("Index", "AlbumManager")'><span>
                    <img src='@Url.Content("~/Content/resources/images/icons/albums.png")' alt="icon" /><br />
                    Albums</span></a></li>
                <li><a class="shortcut-button" href='@Url.Action("Index", "OrderManager")'><span>
                    <img src='@Url.Content("~/Content/resources/images/icons/orders.png")' alt="icon" /><br />
                    Orders</span></a></li>
                <li><a class="shortcut-button" href='@Url.Action("Index", "UserManager")' rel="modal"><span>
                    <img src='@Url.Content("~/Content/resources/images/icons/users.png")' alt="icon" /><br />
                    Users</span></a></li>
            </ul>
            <!-- End .shortcut-buttons-set -->
            <div class="clear">
            </div>
            <div class="content-box">
                @RenderBody()

            </div>

            <div id="footer">
                <small>
                    <!-- Remove this notice or replace it with whatever you want -->
                    &#169; Copyright 2009 Your Company | Powered by <a href="http://themeforest.net/item/simpla-admin-flexible-user-friendly-admin-skin/46073">Simpla Admin</a> | <a href="#">Top</a> </small>
            </div>
            <!-- End #footer -->
        </div>
        <!-- End #main-content -->
        @Scripts.Render("~/bundles/jquery")
        <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
        @RenderSection("scripts", required: false)
        @Scripts.Render("~/bundles/AdminJs")
    </div>
</body>
</html>

MVCMusicStore/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/SiteCss")
    @RenderSection("styles", required: false)
</head>
<body>
    <div id="header">
        <h1>@MVCMusicStore.Views.Resources.SiteTitle</h1>
        <ul id="navlist">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Store", "Index", "Store")</li>
            <li>@Html.Action("_CartButton", "Cart")</li>
            @Html.Partial("_LoginPartial")
        </ul>
    </div>
    <div id="leftMenu">
        @Html.Action("_GenrePartial", "Home")
        <div>
            <a href='@Url.Action("SetLanguage", "Home", new {language = "tr-TR" })' title="Turkce">
                <img src='@Url.Content("~/Content/turkish.png")' alt="Turkce"  /></a>&nbsp;&nbsp;&nbsp;<a href='@Url.Action("SetLanguage", "Home", new {language = "en-US" })' title="English">
                <img src='@Url.Content("~/Content/english.png")' alt="English"  /></a>
        </div>
    </div>
    <div id="main">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>