MVCMusicStore/Controllers/CartController.cs
using MVCMusicStore.Models;
using MVCMusicStore.Tools;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MVCMusicStore.Controllers
{
    public class CartController : Controller
    {

        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _CartButton()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AddToCart(int albumId)
        {
            MyCart myCart = Session["cart"] as MyCart;
            Album added = db.Albums.Find(albumId);
            myCart.AddToCart(new CartItem
            {
                Count = 1,
                Id = albumId,
                Name = added.Title,
                Price = added.Price
            });
            return PartialView("_CartButton");
        }

        public ActionResult _CartItems()
        {
            MyCart myCart = Session["cart"] as MyCart;
            return PartialView(myCart.CartItems);
        }

        public ActionResult RemoveFromCart(int albumId)
        {
            MyCart myCart = Session["cart"] as MyCart;
            myCart.RemoveFromcart(albumId);
            Session["cart"] = myCart;
            return Json(new
            {
                CartButton = RenderRazorViewToString("_CartButton", null),
                CartTable = RenderRazorViewToString("_CartItems", myCart.CartItems).ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Checkout()
        {
            MyCart myCart = Session["cart"] as MyCart;
            UserDetail currentUser = db.UserDetails.Find(WebSecurity.CurrentUserId);
            Tuple<MyCart, UserDetail> t = new Tuple<MyCart, UserDetail>(myCart, currentUser);
            return View(t);
        }

        [HttpPost, ActionName("Checkout")]
        public ActionResult ConfirmCheckout()
        {
            MyCart myCart = Session["cart"] as MyCart;
            UserDetail currentUser = db.UserDetails.Find(WebSecurity.CurrentUserId);
            Order newOrder = new Order()
            {
                Email = currentUser.Email,
                Phone = currentUser.Phone,
                ShipAddress = currentUser.Address,
                UserDetailId = currentUser.Id
            };
            db.Orders.Add(newOrder);
            foreach (var item in myCart.CartItems)
            {
                OrderDetail od = new OrderDetail()
                {
                    Count = item.Count,
                    AlbumId = item.Id,
                    Discount = 0,
                    Order = newOrder,
                    Price = item.Price
                };
                db.OrderDetails.Add(od);
            }
            db.SaveChanges();
            myCart.ClearCart();
            return RedirectToAction("Index", "Home");
        }

        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

MVCMusicStore/Controllers/StoreController.cs
using MVCMusicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities db = new MusicStoreEntities();
        public ActionResult Index()
        {
            return View(db.Genres.ToList());
        }

        public ActionResult Browse(int genreId)
        {
            var selectedGenre = db.Genres.Find(genreId);
            if (selectedGenre == null)
                return RedirectToAction("Index");
            return View(selectedGenre);
        }

        public ActionResult Details(int id)
        {
            var selectedAlbum = db.Albums.Find(id);
            if (selectedAlbum == null)
                return RedirectToAction("Index");
            return View(selectedAlbum);
        }


        public ActionResult RateIt(int vote, int artistId)
        {
            Artist artist = db.Artists.Find(artistId);
            artist.Rating = vote;
            db.SaveChanges();
            return Json(new { Vote=vote, Name= artist.Name, Success="You rate it successfully!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

MVCMusicStore/Views/Store/Browse.cshtml
@model Genre
@{
    ViewBag.Title = "Browse";
}
<h2>Browsing Genre:@Model.Name</h2>
<ul>
    @foreach (var item in Model.Albums)
    {
        <li>@Html.ActionLink(item.Title, "Details", "Store", new { id = item.Id }, null)</li>
    }
</ul>

MVCMusicStore/Views/Store/Details.cshtml
@model Album
@{
    ViewBag.Title = "Details";
}

<h2>Album: @Model.Title</h2>
<br />
<img src='@Url.Content(Model.AlbumArtUrl)'  alt="@Model.Title" width="100" height="75" />
<br />
<p>Genre Name: @Model.Genre.Name</p>
<p>
    Artis Name: @Model.Artist.Name
    <br />
    <div class="rateit" data-rateit-resetable="false" data-productid="@Model.Artist.Id" data-rateit-min="0" data-rateit-max="10" data-rateit-step="1" data-rateit-value="@Model.Artist.Rating"></div>
</p>

<p>Price: @Model.Price.ToString("C2")</p>
<input type="submit" name="btnAddToCart" value="Add To Cart" id="btnAddToCart" onclick="AddToMyCart(@Model.Id)" />

@section Scripts{
    <script src="~/Content/src/jquery.rateit.js"></script>
    <script>
        $(document).ready(function () {
            $(".rateit").bind('rated',function (e) {
                var ri = $(this);
                var value = ri.rateit('value');
                var artistId = ri.data('productid');
                $.ajax({
                    type:"GET",
                    url: '@Url.Action("RateIt", "Store")',
                    data: {vote:value,artistId: artistId},
                    success: function (data) {
                        ri.rateit('readonly',true);
                        alert(data.Success + " You vote " + data.Vote + " for " + data.Name);
                    }
                });
            })   
        });

        function AddToMyCart(id) {
            $.ajax({
                type:"POST",
                url:'@Url.Action("AddToCart", "Cart")',
                data: {albumId:id},
                success:function (data) {
                    $("#navlist li:nth-child(3)").html(data);
                }
            });
        }
    </script>

}

@section Styles {
    <link href="~/Content/src/rateit.css" rel="stylesheet" />
}

MVCMusicStore/Views/Store/Index.cshtml
@model List<Genre>
@{
    ViewBag.Title = "Index";
}

<h2>Store Index</h2>
<p>Selected from @Model.Count genres:</p>
<ul>
    @foreach (var item in Model)
    {
        <li>@Html.ActionLink(item.Name, "Browse", "Store", new { genreId = item.Id }, null)</li>
    }
</ul>